sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t wook3210/docker-react101 -f Dockerfile.dev .

script:
  - docker run -e CI=true wook3210/docker-react101 npm run test -- --coverage

after_success:
  - echo "Test done."

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app:  "docker-react101"
  env:  "DockerReact101-env"
  bucket_name:  "elasticbeanstalk-us-east-2-008832631161"
  bucket_path:  "docker-react101"
  on:
    branch: master    

  access_key_id:  $AWS_ACCESS_KEY
  secret_access_key:  $AWS_SECRET_ACCESS_KEY
